iiot_server:
  tcp_server:
    ip_address: 'localhost'
    port: 1233

  redis_server:
    ip_address: 'localhost'
    port: 6379

  rabbit_mq:
    ip_address: 'localhost'
    port: 5672
    id: 'whaleshark'
    pwd: 'whaleshark'
    exchange: 'facility'
    exchange_type: 'fanout'

  mongodb:
    ip_address: 'localhost'
    port: 27017
    id: 'whaleshark'
    pwd: 'whaleshark'
    db: 'facility'

  influxdb:
    ip_address: 'localhost'
    port: 8086
    id: 'krmim'
    pwd: 'krmin_2017'
    db: 'facility'